openapi: 3.1.0
info:
  version: 1.0.0
  title: Recipes App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of recipes app
tags:
  - name: Auth
    description: Operations related to authentication
  - name: Users
    description: Operations related to users
  - name: Categories
    description: Recipe categories
  - name: Ingredients
    description: Recipe ingredients
servers:
  - url: https://recipes-app.example.com
paths:
    /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../src/swagger/schemas/userRegister.yaml'
      responses:
        '201':
          description: User successfully registered
        '400':
          $ref: '../src/swagger/responses/400.yaml'

  /api/auth/login:
    post:
      summary: User login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../src/swagger/schemas/userLogin.yaml'
      responses:
        '200':
          description: User successfully logged in
        '401':
          $ref: '../src/swagger/responses/401.yaml'

  /api/auth/logout:
    post:
      summary: Logout current user
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User successfully logged out
        '401':
          $ref: '../src/swagger/responses/401.yaml'

  /api/users/me:
    get:
      summary: Get current user info
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                $ref: '../src/swagger/schemas/user.yaml'
        '401':
          $ref: '../src/swagger/responses/401.yaml'

  /api/categories:
    get:
      summary: Get list of recipe categories
      tags:
        - Categories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../src/swagger/schemas/category.yaml'

  /api/ingredients:
    get:
      summary: Get list of ingredients
      tags:
        - Ingredients
      responses:
        '200':
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../src/swagger/schemas/ingredient.yaml'
  /recipes:
    get:
      $ref: ../src/swagger/paths/recipes/get.yaml
  /recipes/{recipeId}:
    get:
      $ref: ../src/swagger/paths/recipes/{recipeId}/get.yaml
  /user/recipes:
    get:
      $ref: ../src/swagger/paths/user/recipes/get.yaml
    post:
      $ref: ../src/swagger/paths/user/recipes/post.yaml
  /user/favorites:
    get:
      $ref: ../src/swagger/paths/user/favorites/get.yaml
  /user/favorites/{recipeId}:
    post:
      $ref: ../src/swagger/paths/user/favorites/{recipeId}/post.yaml
    delete:
      $ref: ../src/swagger/paths/user/favorites/{recipeId}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    Recipe:
      $ref: ../src/swagger/components/schemas/recipes.yaml
    RecipeInput:
      $ref: ../src/swagger/components/schemas/recipeInput.yaml
